Add email id to each comment and sort comments in desc. order
dihim/step pull request #15
Opened 2020-07-07 19:36 UTC by dihim

Added user email and the time they posted to each comment and sorted the array of comments to be displayed by time

- Identified current user logged in DataServlet & added user email and time info to each comment entity
- Sorted the array list of comments in DataServerlet by time

TESTED
I logged in with email and posted a comment and the comment had my email in front of the text with the comment text in the middle ending in the server time it was posted. I posted two more comments which followed the same format but also displayed the most recent comment at the top with other comments in descending order of time

2020-07-12 17:44 UTC, ElanHR requested changes

2020-07-12 17:44 UTC, ElanHR commented on portfolio/src/main/java/com/google/sps/servlets/LoginServlet.java
> +  private String convertToJsonUsingGson(HashMap<String, String> userInfo) {
ditto

2020-07-12 17:44 UTC, ElanHR commented on portfolio/src/main/java/com/google/sps/servlets/LoginServlet.java
> +  public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
Please add a brief comment describing its behavior.

2020-07-13 21:34 UTC, dihim commented on portfolio/src/main/java/com/google/sps/servlets/LoginServlet.java
> +  public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
Gotcha!

2020-07-13 21:36 UTC, dihim commented on portfolio/src/main/java/com/google/sps/servlets/LoginServlet.java
> +  private String convertToJsonUsingGson(HashMap<String, String> userInfo) {
Thanks, will add

2020-07-20 19:47 UTC, ElanHR approved these changes

2020-07-20 19:47 UTC, merged